name: sampiro
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.0
  # flutter: 3.35.1

dependencies:
  app_ui:
    path: packages/app_ui
  auto_route: ^10.1.2
  auto_size_text: ^3.0.0
  bloc: ^9.0.0
  cloud_firestore: ^6.0.0
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  firebase_analytics: ^12.0.0
  firebase_core: ^4.0.0
  firebase_crashlytics: ^5.0.0
  firebase_messaging: ^16.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  fpdart: ^1.1.1
  freezed_annotation: ^3.1.0
  get_it: ^8.2.0
  injectable: ^2.5.1
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logger: ^2.6.1
  package_info_plus: ^8.3.1
  retrofit: ^4.7.2

dev_dependencies:
  auto_route_generator: ^10.2.3
  bloc_test: ^10.0.0
  build_runner: ^2.5.4
  flutter_gen_runner: ^5.11.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^3.1.0
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5
  retrofit_generator: ^9.7.0
  very_good_analysis: ^9.0.0

flutter_gen:
  output: lib/core/resources
  line_length: 120
  fonts:
    enabled: false
  integrations:
    flutter_svg: true

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
