name: sampiro
description: "A new Flutter project."


publish_to: 'none' 













version: 1.0.0+1

environment:
  sdk: ^3.9.0







dependencies:
  flutter:
    sdk: flutter

  
  
  cupertino_icons: ^1.0.8
  auto_route: ^10.1.2
  freezed: ^3.1.0
  get_it: ^8.2.0
  injectable: ^2.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  
  
  
    
  
  flutter_lints: ^5.0.0
  auto_route_generator: ^10.2.3
  build_runner: ^2.5.4





flutter:

  
  
  
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
