// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsRKIGcdTZg9aiDhpJ26hPlCH_wMHnJCo',
    appId: '1:155229538242:web:745afd95858fe42d81f85b',
    messagingSenderId: '155229538242',
    projectId: 'sampiro-flutter-app-dev',
    authDomain: 'sampiro-flutter-app-dev.firebaseapp.com',
    storageBucket: 'sampiro-flutter-app-dev.appspot.com',
    measurementId: 'G-D1V3FV981S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB740odzNtrtiJGa8PUnU7CzukVx3ZyUdo',
    appId: '1:155229538242:android:abbc9285f1e73eba81f85b',
    messagingSenderId: '155229538242',
    projectId: 'sampiro-flutter-app-dev',
    storageBucket: 'sampiro-flutter-app-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA0bBEouonmLC9H_4cLXztQZ7FBK7NwCk',
    appId: '1:155229538242:ios:7949f371b6e2799a81f85b',
    messagingSenderId: '155229538242',
    projectId: 'sampiro-flutter-app-dev',
    storageBucket: 'sampiro-flutter-app-dev.appspot.com',
    iosBundleId: 'com.sampiro.app.development',
  );
}
